name: coverage

on: ["push", "pull_request"]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: tarpaulin
    - name: Generate code coverage
      run: |
        cargo tarpaulin --out Lcov
    - uses: coverallsapp/github-action@v2
